import type { Photo as GalleryPhoto } from 'react-photo-album'
import type { SlideImage } from 'yet-another-react-lightbox'
import type { Photo } from '@/api/types'
import { formatDateTime } from '@/lib/format'

// Long-side sizes generated by the backend (internal/image/derive.go).
const variantSizes = [
  ['thumb', 400],
  ['small', 800],
  ['medium', 1600],
  ['large', 2560],
] as const

function scaled(photo: Photo, long: number): { width: number; height: number } {
  const scale = Math.min(1, long / Math.max(photo.width, photo.height))
  return { width: Math.round(photo.width * scale), height: Math.round(photo.height * scale) }
}

export interface SrcSetEntry {
  src: string
  width: number
  height: number
}

/** One entry per distinct rendered size; a variant equal in size to a
 *  smaller one is dropped (the backend never upscales). */
export function buildSrcSet(photo: Photo): SrcSetEntry[] {
  const out: SrcSetEntry[] = []
  for (const [variant, long] of variantSizes) {
    const dims = scaled(photo, long)
    if (out.some((e) => e.width === dims.width)) continue
    out.push({ src: photo.urls[variant], ...dims })
  }
  return out
}

export type GalleryItem = GalleryPhoto & {
  id: string
  filename: string
  caption?: string
  takenAt?: string
  exif?: Record<string, string>
}

export function toGalleryPhoto(photo: Photo): GalleryItem {
  return {
    key: photo.id,
    id: photo.id,
    src: photo.urls.medium,
    width: photo.width,
    height: photo.height,
    srcSet: buildSrcSet(photo),
    alt: photo.title || photo.filename,
    title: photo.title,
    filename: photo.filename,
    caption: photo.caption,
    takenAt: photo.taken_at,
    exif: photo.exif,
  }
}

export type GallerySlide = SlideImage & {
  download: { url: string; filename: string }
}

export function toSlide(photo: Photo): GallerySlide {
  return {
    src: photo.urls.large,
    width: photo.width,
    height: photo.height,
    srcSet: buildSrcSet(photo),
    alt: photo.title || photo.filename,
    download: { url: photo.urls.download, filename: photo.filename },
  }
}

export interface DetailRow {
  label: string
  value: string
}

/** Rows for the info panel, in display order; fields the plugin did not send are skipped. */
export function photoDetails(photo: Photo): DetailRow[] {
  const exif = photo.exif ?? {}
  const camera = [exif.make, exif.model].filter(Boolean).join(' ')
  // Lightroom's "exposure" is shutter and aperture combined; fall back to the parts.
  const exposure = exif.exposure || [exif.shutter_speed, exif.aperture].filter(Boolean).join(' at ')
  const rows: Array<[string, string | undefined]> = [
    ['Taken', formatDateTime(photo.taken_at)],
    ['Camera', camera],
    ['Lens', exif.lens],
    ['Focal length', exif.focal_length],
    ['Exposure', exposure],
    ['ISO', exif.iso],
    ['Dimensions', `${photo.width} × ${photo.height}`],
    ['Filename', photo.filename],
  ]
  return rows.filter((r): r is [string, string] => !!r[1] && r[1].trim() !== '').map(([label, value]) => ({ label, value }))
}
